services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: image_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    command:
      --max_allowed_packet=64M
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: video_db
    hostname: postgres
    volumes:
      - ./custom-pg_hba.conf:/etc/postgresql/postgresql.conf.sample
      - ./postgresql.conf:/etc/postgresql/postgresql.conf  
      - postgres_data:/var/lib/postgresql/data
      - ./videos:/usr/src/app/videos
    ports:
      - "5432:5432"
    command: ["postgres"]
    networks:
      - app-network

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - postgres
    networks:
      - app-network

volumes:
  mysql_data:
  postgres_data:

networks:
  app-network:
    driver: bridge
